# Assignment: Exploring Data

Hi,

The marketing team would like to share out the five happiest countries of the 2010s on social media.
I’ve attached a notebook that another data scientist started with happiness data inside. I would recommend:
* Creating a list of each country’s highest happiness score, and then sorting it from happiest to least happy country
* Creating a list of each country’s average happiness score, and then sorting it from happiest to least happy country

Are there any differences between the two lists?

Thanks!\
Anna

## Read in the data

In [1]:
# import the data 
import pandas as pd

data_folder = r''happiness_survey_file = 'happiness_survey_data.csv'

In [2]:
df_happiness_survey = pd.read_csv(data_folder + r'\\' + happiness_survey_file)

In [3]:
# there are 2089 rows and 6 columns of data
df_happiness_survey.shape

(2089, 6)

In [4]:
# the years range from 2005 - 2021
# happiness scores range from 2 - 8
df_happiness_survey.describe()

,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
count,2089.000000,2089.000000,2076.000000,2057.000000,2031.000000
mean,2013.727621,5.473747,0.811542,0.745462,63.180326
std,4.455614,1.115567,0.118935,0.140751,6.948546
min,2005.000000,2.178809,0.290184,0.257534,6.720000
25%,2010.000000,4.651972,0.747664,0.651689,58.965000
50%,2014.000000,5.405246,0.834770,0.767357,64.980003
75%,2017.000000,6.294282,0.904682,0.857677,68.362499
max,2021.000000,8.018934,0.987343,0.985178,74.349998

In [5]:
df_happiness_survey.head(3)

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Afghanistan,2008,3.723590,0.450662,0.718114,50.500000
1,Afghanistan,2009,4.401778,0.552308,0.678896,50.799999
2,Afghanistan,2010,4.758381,0.539075,0.600127,51.099998

In [6]:
#Round the numbers to 2 decimal points to make it easier to read
df_happiness_survey = df_happiness_survey.round({'happiness_score':2, 'social_support':2, 'freedom_to_make_life_choices': 2, 'healthy_life_expectancy_at_birth': 2})

In [7]:
df_happiness_survey.head(2)

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Afghanistan,2008,3.72,0.45,0.72,50.5
1,Afghanistan,2009,4.40,0.55,0.68,50.8

## Explore the data

In [8]:
# Filter out any data before 2010 and after 2019
df_happiness_survey = df_happiness_survey.loc[(df_happiness_survey['year'] >= 2010) & (df_happiness_survey['year'] <= 2019)]

In [9]:
# Group the data by country and calculate the maximum happiness score for each one
df_happiness_survey.head(3)

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
2,Afghanistan,2010,4.76,0.54,0.60,51.1
3,Afghanistan,2011,3.83,0.52,0.50,51.4
4,Afghanistan,2012,3.78,0.52,0.53,51.7

In [20]:
# Sort the grouped countries by happiness score and return the top five
happiness_scores_max = df_happiness_survey.groupby('country_name')['happiness_score'].max()

In [21]:
happiness_scores_max.head(5)

country_name
Afghanistan    4.76
Albania        5.87
Algeria        6.35
Angola         5.59
Argentina      6.78
Name: happiness_score, dtype: float64

In [24]:
# Group the data by country and calculate the average happiness score for each one
happiness_scores_avg = df_happiness_survey.groupby('country_name')['happiness_score'].mean().round(2)

In [26]:
happiness_scores_avg.head(5)

country_name
Afghanistan    3.50
Albania        4.98
Algeria        5.39
Angola         4.42
Argentina      6.40
Name: happiness_score, dtype: float64

In [28]:
# Sort the grouped countries by happiness score and return the top five
sort_happiness_scores_max = happiness_scores_max.sort_values(ascending=False)

country_name
Finland        7.86
Denmark        7.79
Switzerland    7.78
Norway         7.68
Canada         7.65
Name: happiness_score, dtype: float64

In [29]:
sort_happiness_scores_avg = happiness_scores_avg.sort_values(ascending=False)

country_name
Denmark        7.62
Switzerland    7.57
Finland        7.55
Norway         7.54
Iceland        7.52
Name: happiness_score, dtype: float64

In [31]:
# Compare the two lists
sort_happiness_scores_max.head(5)

country_name
Finland        7.86
Denmark        7.79
Switzerland    7.78
Norway         7.68
Canada         7.65
Name: happiness_score, dtype: float64

In [32]:
sort_happiness_scores_avg.head(5)

country_name
Denmark        7.62
Switzerland    7.57
Finland        7.55
Norway         7.54
Iceland        7.52
Name: happiness_score, dtype: float64

In [35]:
df_happiness_survey[df_happiness_survey['country_name'].isin(['Finland', 'Denmark', 'Switzerland', 'Norway'])]

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
481,Denmark,2010,7.77,0.97,0.94,69.40
482,Denmark,2011,7.79,0.96,0.93,69.62
483,Denmark,2012,7.52,0.95,0.93,69.84
484,Denmark,2013,7.59,0.96,0.92,70.06
485,Denmark,2014,7.51,0.96,0.94,70.28
486,Denmark,2015,7.51,0.96,0.94,70.50
487,Denmark,2016,7.56,0.95,0.95,70.62
488,Denmark,2017,7.59,0.95,0.96,70.75
489,Denmark,2018,7.65,0.96,0.94,70.88
490,Denmark,2019,7.69,0.96,0.96,71.00
590,Finland,2010,7.39,0.94,0.92,69.60
591,Finland,2011,7.35,0.94,0.94,69.82
592,Finland,2012,7.42,0.93,0.92,70.04
593,Finland,2013,7.44,0.94,0.92,70.26
594,Finland,2014,7.38,0.95,0.93,70.48
595,Finland,2015,7.45,0.95,0.93,70.70
596,Finland,2016,7.66,0.95,0.95,70.78
597,Finland,2017,7.79,0.96,0.96,70.85
598,Finland,2018,7.86,0.96,0.94,70.93
599,Finland,2019,7.78,0.94,0.95,71.00
1396,Norway,2012,7.68,0.95,0.95,70.60
1397,Norway,2014,7.44,0.94,0.96,71.00
1398,Norway,2015,7.60,0.95,0.95,71.20
1399,Norway,2016,7.60,0.96,0.95,71.25
1400,Norway,2017,7.58,0.95,0.95,71.30
1401,Norway,2018,7.44,0.97,0.96,71.35
1402,Norway,2019,7.44,0.94,0.95,71.40
1773,Switzerland,2012,7.78,0.95,0.95,71.52
1774,Switzerland,2014,7.49,0.96,0.95,71.64
1775,Switzerland,2015,7.57,0.94,0.93,71.70
1776,Switzerland,2016,7.46,0.93,0.93,71.90
1777,Switzerland,2017,7.47,0.95,0.92,72.10
1778,Switzerland,2018,7.51,0.93,0.93,72.30
1779,Switzerland,2019,7.69,0.95,0.91,72.50